### ISSUE TITLE
How the inputs input into the CNNs 

### ISSUE THREAD

**Issue by guoyang007** [garythung/torch-lrcn#3]
i know  in  every iteration the input is 8 frames,but how to make every frame into a CNN and then gather the outputs of the CNN  into LSTM? Or just the table type in Lua help us do this?
 I'm new to Torch，the above make me  so confused .

**Comment by garythung** [comment]
Hi Guoyang,

First off, thank you for checking out the repository.

In `DataLoader.lua`, when we retrieve a new batch, we first create the `videoData` table which will hold `batchSize` `videoTensor`s, which are represented as `seqLength` frames. Thus, the shape of a `videoTensor` is `seqLength x numChannels x scaledHeight x scaledWidth`. Then when we call 

> `data = torch.cat(videoData, 1):type('torch.FloatTensor')`

[(see torch.cat docs here if desired)](https://github.com/torch/torch7/blob/master/doc/maths.md#res-torchcat-res-x_1-x_2-dimension-)

`data` will be a tensor of size `(batchSize * seqLength) x numChannels x scaledHeight x scaledWidth`. As per the [docs](https://github.com/torch/nn/blob/master/doc/convolution.md#nn.SpatialConvolution), the convolutional layers are expecting data of shape `nInputPlane x height x width`, where there is a first, implicit dimension that is the batch size. The CNN will output a vector of size `n` for each frame, which is an encoding of the features, and the LSTM will gather every `seqLength` vectors as input (i.e. one video) to finally output scores for each class for a video.

I hope that helps alleviate your confusion.

-Gary
